[package]
name = "null_box"
version = "0.1.0"
authors = ["Sebastian <sebjfk@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = { path = "/home/sebastian/Documents/godot-rust/gdnative" }
bincode = "1.0"
crossbeam-channel = "0.3"
laminar = "0.2.2"
serde = "1.0"
serde_derive = "1.0"