[package]
name = "nullbox_server"
version = "0.1.0"
authors = ["Sebastian <sebjfk@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.0"
crossbeam-channel = "0.3"
laminar = "0.2.2"
serde = "1.0"
serde_derive = "1.0"
nullbox_core = { path = "../nullbox_core" }